### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [nrc/rls-data#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by nrc** [comment]
We use it because this crate is used by the compiler and the compiler can't use Serde. I don't think there is any hope of the compiler using proc macros soon, so I don't think we can fix this...

**Comment by dtolnay** [comment]
That's too bad! Thanks for the explanation.
