### ISSUE TITLE
Can't distinguish foreign functions from non-foreign functions.

### ISSUE THREAD

**Issue by emilio** [nrc/rls-data#17]
Which I need to be able to link to functions from C++. I can tag them manually with no_mangle from bindgen, which does the trick, but ideally it wouldn't be needed.

I'm filing instead of writing a PR directly because I don't know the process (I know rustc also needs to be updated), and also because I don't know what's the best way to fix it.

I can imagine `DefKind::ForeignFunction` / `DefKind::ForeignStatic`, but also maybe just a `is_foreign` enum / boolean in `Def`.

WDYT @nrc? I'm happy to send patches for whatever is needed :)

**Comment by nrc** [comment]
Adding a `bool` to `Def` sounds better to me because then clients who don't care won't be affected. Alternatively, you could just add it to function and static `DefKind`s. Whichever is easier, really.
